// German verbs & present-tense conjugations (from class whiteboard)
// Pronouns order: ich | du | er/sie/es | wir | ihr | sie/Sie

export const PRONOUNS = ['ich', 'du', 'er/sie/es', 'wir', 'ihr', 'sie/Sie'];

export const GERMAN_VERBS = [
  // ── Very irregular ─────────────────────────────────────────────────────────
  {
    id: 1,
    infinitive: 'sein',
    en: 'to be',
    es: 'ser / estar',
    type: 'irregular',
    stemChange: null,
    note: { en: 'Highly irregular — must be memorized', es: 'Muy irregular — hay que memorizarlo' },
    forms: {
      'ich':      { form: 'bin',   highlight: true },
      'du':       { form: 'bist',  highlight: true },
      'er/sie/es':{ form: 'ist',   highlight: true },
      'wir':      { form: 'sind',  highlight: true },
      'ihr':      { form: 'seid',  highlight: true },
      'sie/Sie':  { form: 'sind',  highlight: true },
    },
  },
  {
    id: 2,
    infinitive: 'haben',
    en: 'to have',
    es: 'tener',
    type: 'irregular',
    stemChange: null,
    note: { en: 'Irregular in du and er/sie/es forms', es: 'Irregular en las formas du y er/sie/es' },
    forms: {
      'ich':      { form: 'habe',  highlight: false },
      'du':       { form: 'hast',  highlight: true  },
      'er/sie/es':{ form: 'hat',   highlight: true  },
      'wir':      { form: 'haben', highlight: false },
      'ihr':      { form: 'habt',  highlight: false },
      'sie/Sie':  { form: 'haben', highlight: false },
    },
  },
  // ── Stem-vowel change e → i ─────────────────────────────────────────────
  {
    id: 3,
    infinitive: 'essen',
    en: 'to eat',
    es: 'comer',
    type: 'irregular',
    stemChange: 'e → i',
    note: { en: 'Stem vowel changes e → i in du and er/sie/es', es: 'La vocal del radical cambia e → i en du y er/sie/es' },
    forms: {
      'ich':      { form: 'esse',  highlight: false },
      'du':       { form: 'isst',  highlight: true  },
      'er/sie/es':{ form: 'isst',  highlight: true  },
      'wir':      { form: 'essen', highlight: false },
      'ihr':      { form: 'esst',  highlight: false },
      'sie/Sie':  { form: 'essen', highlight: false },
    },
  },
  {
    id: 4,
    infinitive: 'sprechen',
    en: 'to speak',
    es: 'hablar',
    type: 'irregular',
    stemChange: 'e → i',
    note: { en: 'Stem vowel changes e → i in du and er/sie/es', es: 'La vocal del radical cambia e → i en du y er/sie/es' },
    forms: {
      'ich':      { form: 'spreche',  highlight: false },
      'du':       { form: 'sprichst', highlight: true  },
      'er/sie/es':{ form: 'spricht',  highlight: true  },
      'wir':      { form: 'sprechen', highlight: false },
      'ihr':      { form: 'sprecht',  highlight: false },
      'sie/Sie':  { form: 'sprechen', highlight: false },
    },
  },
  // ── Stem-vowel change e → ie ────────────────────────────────────────────
  {
    id: 5,
    infinitive: 'sehen',
    en: 'to see',
    es: 'ver',
    type: 'irregular',
    stemChange: 'e → ie',
    note: { en: 'Stem vowel changes e → ie in du and er/sie/es', es: 'La vocal del radical cambia e → ie en du y er/sie/es' },
    forms: {
      'ich':      { form: 'sehe',   highlight: false },
      'du':       { form: 'siehst', highlight: true  },
      'er/sie/es':{ form: 'sieht',  highlight: true  },
      'wir':      { form: 'sehen',  highlight: false },
      'ihr':      { form: 'seht',   highlight: false },
      'sie/Sie':  { form: 'sehen',  highlight: false },
    },
  },
  {
    id: 6,
    infinitive: 'lesen',
    en: 'to read',
    es: 'leer',
    type: 'irregular',
    stemChange: 'e → ie',
    note: { en: 'Stem vowel changes e → ie in du and er/sie/es', es: 'La vocal del radical cambia e → ie en du y er/sie/es' },
    forms: {
      'ich':      { form: 'lese',  highlight: false },
      'du':       { form: 'liest', highlight: true  },
      'er/sie/es':{ form: 'liest', highlight: true  },
      'wir':      { form: 'lesen', highlight: false },
      'ihr':      { form: 'lest',  highlight: false },
      'sie/Sie':  { form: 'lesen', highlight: false },
    },
  },
  // ── Regular verbs ───────────────────────────────────────────────────────
  {
    id: 7,
    infinitive: 'gehen',
    en: 'to go',
    es: 'ir',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'gehe',   highlight: false },
      'du':       { form: 'gehst',  highlight: false },
      'er/sie/es':{ form: 'geht',   highlight: false },
      'wir':      { form: 'gehen',  highlight: false },
      'ihr':      { form: 'geht',   highlight: false },
      'sie/Sie':  { form: 'gehen',  highlight: false },
    },
  },
  {
    id: 8,
    infinitive: 'reisen',
    en: 'to travel',
    es: 'viajar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'reise',   highlight: false },
      'du':       { form: 'reist',   highlight: false },
      'er/sie/es':{ form: 'reist',   highlight: false },
      'wir':      { form: 'reisen',  highlight: false },
      'ihr':      { form: 'reist',   highlight: false },
      'sie/Sie':  { form: 'reisen',  highlight: false },
    },
  },
  {
    id: 9,
    infinitive: 'singen',
    en: 'to sing',
    es: 'cantar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'singe',   highlight: false },
      'du':       { form: 'singst',  highlight: false },
      'er/sie/es':{ form: 'singt',   highlight: false },
      'wir':      { form: 'singen',  highlight: false },
      'ihr':      { form: 'singt',   highlight: false },
      'sie/Sie':  { form: 'singen',  highlight: false },
    },
  },
  {
    id: 10,
    infinitive: 'fliegen',
    en: 'to fly',
    es: 'volar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'fliege',   highlight: false },
      'du':       { form: 'fliegst',  highlight: false },
      'er/sie/es':{ form: 'fliegt',   highlight: false },
      'wir':      { form: 'fliegen',  highlight: false },
      'ihr':      { form: 'fliegt',   highlight: false },
      'sie/Sie':  { form: 'fliegen',  highlight: false },
    },
  },
  {
    id: 11,
    infinitive: 'spielen',
    en: 'to play',
    es: 'jugar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'spiele',   highlight: false },
      'du':       { form: 'spielst',  highlight: false },
      'er/sie/es':{ form: 'spielt',   highlight: false },
      'wir':      { form: 'spielen',  highlight: false },
      'ihr':      { form: 'spielt',   highlight: false },
      'sie/Sie':  { form: 'spielen',  highlight: false },
    },
  },
  {
    id: 12,
    infinitive: 'joggen',
    en: 'to jog',
    es: 'trotar / hacer jogging',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'jogge',   highlight: false },
      'du':       { form: 'joggst',  highlight: false },
      'er/sie/es':{ form: 'joggt',   highlight: false },
      'wir':      { form: 'joggen',  highlight: false },
      'ihr':      { form: 'joggt',   highlight: false },
      'sie/Sie':  { form: 'joggen',  highlight: false },
    },
  },
  {
    id: 13,
    infinitive: 'trinken',
    en: 'to drink',
    es: 'beber / tomar',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'trinke',   highlight: false },
      'du':       { form: 'trinkst',  highlight: false },
      'er/sie/es':{ form: 'trinkt',   highlight: false },
      'wir':      { form: 'trinken',  highlight: false },
      'ihr':      { form: 'trinkt',   highlight: false },
      'sie/Sie':  { form: 'trinken',  highlight: false },
    },
  },
  {
    id: 14,
    infinitive: 'machen',
    en: 'to make / to do',
    es: 'hacer',
    type: 'regular',
    stemChange: null,
    note: null,
    forms: {
      'ich':      { form: 'mache',   highlight: false },
      'du':       { form: 'machst',  highlight: false },
      'er/sie/es':{ form: 'macht',   highlight: false },
      'wir':      { form: 'machen',  highlight: false },
      'ihr':      { form: 'macht',   highlight: false },
      'sie/Sie':  { form: 'machen',  highlight: false },
    },
  },
  {
    id: 15,
    infinitive: 'arbeiten',
    en: 'to work',
    es: 'trabajar',
    type: 'regular',
    stemChange: null,
    // arbeiten: stem ends in -t, so add -e- before -st and -t endings
    note: { en: 'Stem ends in -t: adds -e- before -st and -t endings', es: 'El radical termina en -t: se añade -e- antes de -st y -t' },
    forms: {
      'ich':      { form: 'arbeite',    highlight: false },
      'du':       { form: 'arbeitest',  highlight: true  },
      'er/sie/es':{ form: 'arbeitet',   highlight: true  },
      'wir':      { form: 'arbeiten',   highlight: false },
      'ihr':      { form: 'arbeitet',   highlight: true  },
      'sie/Sie':  { form: 'arbeiten',   highlight: false },
    },
  },
];
