export const RUSSIAN_VOCABULARY_QUIZ = {
  en: [
    { id: 1, word: "Привет", ipa: "pri-VYET", question: "What does 'Привет' mean?", options: ["Hi / Hello", "Goodbye", "Thank you", "Please"], correctIndex: 0, reference: "Greeting" },
    { id: 2, word: "Здравствуйте", ipa: "ZDRA-stvuy-tye", question: "What does 'Здравствуйте' mean?", options: ["Hello (formal)", "Goodbye", "Good morning", "Excuse me"], correctIndex: 0, reference: "Greeting" },
    { id: 3, word: "До свидания", ipa: "da svi-DA-ni-ya", question: "What does 'До свидания' mean?", options: ["Goodbye", "Hello", "See you later", "Good night"], correctIndex: 0, reference: "Farewell" },
    { id: 4, word: "Пока", ipa: "pa-KA", question: "What does 'Пока' mean?", options: ["Bye (informal)", "Hello", "Wait", "Now"], correctIndex: 0, reference: "Farewell" },
    { id: 5, word: "Спасибо", ipa: "spa-SI-ba", question: "What does 'Спасибо' mean?", options: ["Thank you", "Please", "Sorry", "Yes"], correctIndex: 0, reference: "Courtesy" },
    { id: 6, word: "Пожалуйста", ipa: "pa-ZHA-luy-sta", question: "What does 'Пожалуйста' mean?", options: ["Please / You're welcome", "Thank you", "Excuse me", "No"], correctIndex: 0, reference: "Courtesy" },
    { id: 7, word: "Извините", ipa: "iz-vi-NI-tye", question: "What does 'Извините' mean?", options: ["Excuse me / Sorry", "Thank you", "Please", "Goodbye"], correctIndex: 0, reference: "Courtesy" },
    { id: 8, word: "Да", ipa: "da", question: "What does 'Да' mean?", options: ["Yes", "No", "Maybe", "And"], correctIndex: 0, reference: "Basic" },
    { id: 9, word: "Нет", ipa: "nyet", question: "What does 'Нет' mean?", options: ["No", "Yes", "Not", "Never"], correctIndex: 0, reference: "Basic" },
    { id: 10, word: "Доброе утро", ipa: "DOB-ra-ye U-tra", question: "What does 'Доброе утро' mean?", options: ["Good morning", "Good evening", "Good night", "Good afternoon"], correctIndex: 0, reference: "Greeting" },
    { id: 11, word: "Добрый вечер", ipa: "DOB-riy VYE-chyer", question: "What does 'Добрый вечер' mean?", options: ["Good evening", "Good morning", "Good night", "Good afternoon"], correctIndex: 0, reference: "Greeting" },
    { id: 12, word: "Спокойной ночи", ipa: "spa-KOY-nay NO-chi", question: "What does 'Спокойной ночи' mean?", options: ["Good night", "Good morning", "Good evening", "Sweet dreams"], correctIndex: 0, reference: "Greeting" },
    { id: 13, word: "Вода", ipa: "va-DA", question: "What does 'Вода' mean?", options: ["Water", "Fire", "Air", "Earth"], correctIndex: 0, reference: "Noun" },
    { id: 14, word: "Хлеб", ipa: "khlyeb", question: "What does 'Хлеб' mean?", options: ["Bread", "Milk", "Meat", "Salt"], correctIndex: 0, reference: "Noun" },
    { id: 15, word: "Дом", ipa: "dom", question: "What does 'Дом' mean?", options: ["House / Home", "Street", "City", "School"], correctIndex: 0, reference: "Noun" },
    { id: 16, word: "Семья", ipa: "syem-YA", question: "What does 'Семья' mean?", options: ["Family", "Friend", "Neighbor", "Nation"], correctIndex: 0, reference: "Noun" },
    { id: 17, word: "Друг", ipa: "druk", question: "What does 'Друг' mean?", options: ["Friend", "Enemy", "Brother", "Stranger"], correctIndex: 0, reference: "Noun" },
    { id: 18, word: "Любовь", ipa: "lyu-BOV", question: "What does 'Любовь' mean?", options: ["Love", "Peace", "Joy", "Hope"], correctIndex: 0, reference: "Noun" },
    { id: 19, word: "Жизнь", ipa: "zhizn", question: "What does 'Жизнь' mean?", options: ["Life", "Death", "Soul", "World"], correctIndex: 0, reference: "Noun" },
    { id: 20, word: "Мир", ipa: "mir", question: "What does 'Мир' mean?", options: ["World / Peace", "War", "City", "Country"], correctIndex: 0, reference: "Noun" },
    { id: 21, word: "Время", ipa: "VRY-e-mya", question: "What does 'Время' mean?", options: ["Time", "Day", "Night", "Hour"], correctIndex: 0, reference: "Noun" },
    { id: 22, word: "Работа", ipa: "ra-BO-ta", question: "What does 'Работа' mean?", options: ["Work / Job", "Rest", "Play", "School"], correctIndex: 0, reference: "Noun" },
    { id: 23, word: "Школа", ipa: "SHKO-la", question: "What does 'Школа' mean?", options: ["School", "Church", "Market", "Hospital"], correctIndex: 0, reference: "Noun" },
    { id: 24, word: "Книга", ipa: "KNI-ga", question: "What does 'Книга' mean?", options: ["Book", "Pen", "Paper", "Letter"], correctIndex: 0, reference: "Noun" },
    { id: 25, word: "Деньги", ipa: "DYEN-gi", question: "What does 'Деньги' mean?", options: ["Money", "Gold", "Price", "Bank"], correctIndex: 0, reference: "Noun" },
    { id: 26, word: "Город", ipa: "GO-rat", question: "What does 'Город' mean?", options: ["City / Town", "Village", "Country", "Street"], correctIndex: 0, reference: "Noun" },
    { id: 27, word: "Страна", ipa: "stra-NA", question: "What does 'Страна' mean?", options: ["Country", "City", "Region", "World"], correctIndex: 0, reference: "Noun" },
    { id: 28, word: "Язык", ipa: "ya-ZIK", question: "What does 'Язык' mean?", options: ["Language / Tongue", "Voice", "Speech", "Word"], correctIndex: 0, reference: "Noun" },
    { id: 29, word: "Человек", ipa: "chye-la-VYEK", question: "What does 'Человек' mean?", options: ["Person / Human", "Animal", "Child", "Adult"], correctIndex: 0, reference: "Noun" },
    { id: 30, word: "Ребёнок", ipa: "rye-BYO-nak", question: "What does 'Ребёнок' mean?", options: ["Child", "Baby", "Youth", "Adult"], correctIndex: 0, reference: "Noun" },
    { id: 31, word: "Сердце", ipa: "SYER-tse", question: "What does 'Сердце' mean?", options: ["Heart", "Soul", "Mind", "Spirit"], correctIndex: 0, reference: "Noun" },
    { id: 32, word: "Душа", ipa: "du-SHA", question: "What does 'Душа' mean?", options: ["Soul", "Heart", "Mind", "Spirit"], correctIndex: 0, reference: "Noun" },
    { id: 33, word: "Бог", ipa: "bok", question: "What does 'Бог' mean?", options: ["God", "Angel", "Heaven", "Faith"], correctIndex: 0, reference: "Noun" },
    { id: 34, word: "Вера", ipa: "VYE-ra", question: "What does 'Вера' mean?", options: ["Faith / Belief", "Hope", "Love", "Truth"], correctIndex: 0, reference: "Noun" },
    { id: 35, word: "Правда", ipa: "PRAV-da", question: "What does 'Правда' mean?", options: ["Truth", "Lie", "Secret", "Word"], correctIndex: 0, reference: "Noun" },
    { id: 36, word: "Надежда", ipa: "na-DYEZH-da", question: "What does 'Надежда' mean?", options: ["Hope", "Fear", "Doubt", "Despair"], correctIndex: 0, reference: "Noun" },
    { id: 37, word: "Свобода", ipa: "sva-BO-da", question: "What does 'Свобода' mean?", options: ["Freedom", "Power", "Justice", "Order"], correctIndex: 0, reference: "Noun" },
    { id: 38, word: "Солнце", ipa: "SON-tse", question: "What does 'Солнце' mean?", options: ["Sun", "Moon", "Star", "Cloud"], correctIndex: 0, reference: "Noun" },
    { id: 39, word: "Природа", ipa: "pri-RO-da", question: "What does 'Природа' mean?", options: ["Nature", "Culture", "Art", "Science"], correctIndex: 0, reference: "Noun" },
    { id: 40, word: "Счастье", ipa: "SHAS-tye", question: "What does 'Счастье' mean?", options: ["Happiness", "Sadness", "Joy", "Luck"], correctIndex: 0, reference: "Noun" }
  ],
  es: [
    { id: 1, word: "Привет", ipa: "pri-VYET", question: "¿Qué significa 'Привет'?", options: ["Hola (informal)", "Adiós", "Gracias", "Por favor"], correctIndex: 0, reference: "Saludo" },
    { id: 2, word: "Здравствуйте", ipa: "ZDRA-stvuy-tye", question: "¿Qué significa 'Здравствуйте'?", options: ["Hola (formal)", "Adiós", "Buenos días", "Disculpe"], correctIndex: 0, reference: "Saludo" },
    { id: 3, word: "До свидания", ipa: "da svi-DA-ni-ya", question: "¿Qué significa 'До свидания'?", options: ["Adiós", "Hola", "Hasta luego", "Buenas noches"], correctIndex: 0, reference: "Despedida" },
    { id: 4, word: "Пока", ipa: "pa-KA", question: "¿Qué significa 'Пока'?", options: ["Chao (informal)", "Hola", "Espera", "Ahora"], correctIndex: 0, reference: "Despedida" },
    { id: 5, word: "Спасибо", ipa: "spa-SI-ba", question: "¿Qué significa 'Спасибо'?", options: ["Gracias", "Por favor", "Lo siento", "Sí"], correctIndex: 0, reference: "Cortesía" },
    { id: 6, word: "Пожалуйста", ipa: "pa-ZHA-luy-sta", question: "¿Qué significa 'Пожалуйста'?", options: ["Por favor / De nada", "Gracias", "Perdón", "No"], correctIndex: 0, reference: "Cortesía" },
    { id: 7, word: "Извините", ipa: "iz-vi-NI-tye", question: "¿Qué significa 'Извините'?", options: ["Perdón / Disculpe", "Gracias", "Por favor", "Adiós"], correctIndex: 0, reference: "Cortesía" },
    { id: 8, word: "Да", ipa: "da", question: "¿Qué significa 'Да'?", options: ["Sí", "No", "Quizás", "Y"], correctIndex: 0, reference: "Básico" },
    { id: 9, word: "Нет", ipa: "nyet", question: "¿Qué significa 'Нет'?", options: ["No", "Sí", "Nunca", "Nada"], correctIndex: 0, reference: "Básico" },
    { id: 10, word: "Доброе утро", ipa: "DOB-ra-ye U-tra", question: "¿Qué significa 'Доброе утро'?", options: ["Buenos días", "Buenas noches", "Buenas tardes", "Buenas noches"], correctIndex: 0, reference: "Saludo" },
    { id: 11, word: "Добрый вечер", ipa: "DOB-riy VYE-chyer", question: "¿Qué significa 'Добрый вечер'?", options: ["Buenas noches", "Buenos días", "Buenas noches", "Buenas tardes"], correctIndex: 0, reference: "Saludo" },
    { id: 12, word: "Спокойной ночи", ipa: "spa-KOY-nay NO-chi", question: "¿Qué significa 'Спокойной ночи'?", options: ["Buenas noches", "Buenos días", "Buenas tardes", "Dulces sueños"], correctIndex: 0, reference: "Saludo" },
    { id: 13, word: "Вода", ipa: "va-DA", question: "¿Qué significa 'Вода'?", options: ["Agua", "Fuego", "Aire", "Tierra"], correctIndex: 0, reference: "Sustantivo" },
    { id: 14, word: "Хлеб", ipa: "khlyeb", question: "¿Qué significa 'Хлеб'?", options: ["Pan", "Leche", "Carne", "Sal"], correctIndex: 0, reference: "Sustantivo" },
    { id: 15, word: "Дом", ipa: "dom", question: "¿Qué significa 'Дом'?", options: ["Casa / Hogar", "Calle", "Ciudad", "Escuela"], correctIndex: 0, reference: "Sustantivo" },
    { id: 16, word: "Семья", ipa: "syem-YA", question: "¿Qué significa 'Семья'?", options: ["Familia", "Amigo", "Vecino", "Nación"], correctIndex: 0, reference: "Sustantivo" },
    { id: 17, word: "Друг", ipa: "druk", question: "¿Qué significa 'Друг'?", options: ["Amigo", "Enemigo", "Hermano", "Extraño"], correctIndex: 0, reference: "Sustantivo" },
    { id: 18, word: "Любовь", ipa: "lyu-BOV", question: "¿Qué significa 'Любовь'?", options: ["Amor", "Paz", "Alegría", "Esperanza"], correctIndex: 0, reference: "Sustantivo" },
    { id: 19, word: "Жизнь", ipa: "zhizn", question: "¿Qué significa 'Жизнь'?", options: ["Vida", "Muerte", "Alma", "Mundo"], correctIndex: 0, reference: "Sustantivo" },
    { id: 20, word: "Мир", ipa: "mir", question: "¿Qué significa 'Мир'?", options: ["Mundo / Paz", "Guerra", "Ciudad", "País"], correctIndex: 0, reference: "Sustantivo" },
    { id: 21, word: "Время", ipa: "VRY-e-mya", question: "¿Qué significa 'Время'?", options: ["Tiempo", "Día", "Noche", "Hora"], correctIndex: 0, reference: "Sustantivo" },
    { id: 22, word: "Работа", ipa: "ra-BO-ta", question: "¿Qué significa 'Работа'?", options: ["Trabajo", "Descanso", "Juego", "Escuela"], correctIndex: 0, reference: "Sustantivo" },
    { id: 23, word: "Школа", ipa: "SHKO-la", question: "¿Qué significa 'Школа'?", options: ["Escuela", "Iglesia", "Mercado", "Hospital"], correctIndex: 0, reference: "Sustantivo" },
    { id: 24, word: "Книга", ipa: "KNI-ga", question: "¿Qué significa 'Книга'?", options: ["Libro", "Pluma", "Papel", "Carta"], correctIndex: 0, reference: "Sustantivo" },
    { id: 25, word: "Деньги", ipa: "DYEN-gi", question: "¿Qué significa 'Деньги'?", options: ["Dinero", "Oro", "Precio", "Banco"], correctIndex: 0, reference: "Sustantivo" },
    { id: 26, word: "Город", ipa: "GO-rat", question: "¿Qué significa 'Город'?", options: ["Ciudad", "Pueblo", "País", "Calle"], correctIndex: 0, reference: "Sustantivo" },
    { id: 27, word: "Страна", ipa: "stra-NA", question: "¿Qué significa 'Страна'?", options: ["País", "Ciudad", "Región", "Mundo"], correctIndex: 0, reference: "Sustantivo" },
    { id: 28, word: "Язык", ipa: "ya-ZIK", question: "¿Qué significa 'Язык'?", options: ["Idioma / Lengua", "Voz", "Habla", "Palabra"], correctIndex: 0, reference: "Sustantivo" },
    { id: 29, word: "Человек", ipa: "chye-la-VYEK", question: "¿Qué significa 'Человек'?", options: ["Persona / Humano", "Animal", "Niño", "Adulto"], correctIndex: 0, reference: "Sustantivo" },
    { id: 30, word: "Ребёнок", ipa: "rye-BYO-nak", question: "¿Qué significa 'Ребёнок'?", options: ["Niño", "Bebé", "Joven", "Adulto"], correctIndex: 0, reference: "Sustantivo" },
    { id: 31, word: "Сердце", ipa: "SYER-tse", question: "¿Qué significa 'Сердце'?", options: ["Corazón", "Alma", "Mente", "Espíritu"], correctIndex: 0, reference: "Sustantivo" },
    { id: 32, word: "Душа", ipa: "du-SHA", question: "¿Qué significa 'Душа'?", options: ["Alma", "Corazón", "Mente", "Espíritu"], correctIndex: 0, reference: "Sustantivo" },
    { id: 33, word: "Бог", ipa: "bok", question: "¿Qué significa 'Бог'?", options: ["Dios", "Ángel", "Cielo", "Fe"], correctIndex: 0, reference: "Sustantivo" },
    { id: 34, word: "Вера", ipa: "VYE-ra", question: "¿Qué significa 'Вера'?", options: ["Fe / Creencia", "Esperanza", "Amor", "Verdad"], correctIndex: 0, reference: "Sustantivo" },
    { id: 35, word: "Правда", ipa: "PRAV-da", question: "¿Qué significa 'Правда'?", options: ["Verdad", "Mentira", "Secreto", "Palabra"], correctIndex: 0, reference: "Sustantivo" },
    { id: 36, word: "Надежда", ipa: "na-DYEZH-da", question: "¿Qué significa 'Надежда'?", options: ["Esperanza", "Miedo", "Duda", "Desesperación"], correctIndex: 0, reference: "Sustantivo" },
    { id: 37, word: "Свобода", ipa: "sva-BO-da", question: "¿Qué significa 'Свобода'?", options: ["Libertad", "Poder", "Justicia", "Orden"], correctIndex: 0, reference: "Sustantivo" },
    { id: 38, word: "Солнце", ipa: "SON-tse", question: "¿Qué significa 'Солнце'?", options: ["Sol", "Luna", "Estrella", "Nube"], correctIndex: 0, reference: "Sustantivo" },
    { id: 39, word: "Природа", ipa: "pri-RO-da", question: "¿Qué significa 'Природа'?", options: ["Naturaleza", "Cultura", "Arte", "Ciencia"], correctIndex: 0, reference: "Sustantivo" },
    { id: 40, word: "Счастье", ipa: "SHAS-tye", question: "¿Qué significa 'Счастье'?", options: ["Felicidad", "Tristeza", "Alegría", "Suerte"], correctIndex: 0, reference: "Sustantivo" }
  ]
};
