export const RUSSIAN_ADJECTIVE_CARDS = [
  { id: 1,  en: 'big',       es: 'grande',    ru: 'большой',     translit: 'bol-SHOY',     emoji: '🔴' },
  { id: 2,  en: 'small',     es: 'pequeño',   ru: 'маленький',   translit: 'MA-len-kiy',   emoji: '🔵' },
  { id: 3,  en: 'tall',      es: 'alto',      ru: 'высокий',     translit: 'vy-SO-kiy',    emoji: '🏔️' },
  { id: 4,  en: 'short',     es: 'bajo/corto',ru: 'короткий',    translit: 'ko-ROT-kiy',   emoji: '📏' },
  { id: 5,  en: 'ugly',      es: 'feo',       ru: 'некрасивый',  translit: 'ne-kra-SI-vy', emoji: '😤' },
  { id: 6,  en: 'beautiful', es: 'hermoso',   ru: 'красивый',    translit: 'kra-SI-vy',    emoji: '🌸' },
  { id: 7,  en: 'fast',      es: 'rápido',    ru: 'быстрый',     translit: 'BYS-try',      emoji: '⚡' },
  { id: 8,  en: 'slow',      es: 'lento',     ru: 'медленный',   translit: 'MED-len-ny',   emoji: '🐢' },
  { id: 9,  en: 'old',       es: 'viejo',     ru: 'старый',      translit: 'STA-ry',       emoji: '👴' },
  { id: 10, en: 'young',     es: 'joven',     ru: 'молодой',     translit: 'mo-lo-DOY',    emoji: '🧒' },
  { id: 11, en: 'hot',       es: 'caliente',  ru: 'горячий',     translit: 'go-RYA-chiy',  emoji: '🔥' },
  { id: 12, en: 'cold',      es: 'frío',      ru: 'холодный',    translit: 'kho-LOD-ny',   emoji: '❄️' },
  { id: 13, en: 'good',      es: 'bueno',     ru: 'хороший',     translit: 'kho-RO-shiy',  emoji: '✅' },
  { id: 14, en: 'bad',       es: 'malo',      ru: 'плохой',      translit: 'plo-KHOY',     emoji: '❌' },
  { id: 15, en: 'happy',     es: 'feliz',     ru: 'счастливый',  translit: 'schast-LI-vy', emoji: '😊' },
  { id: 16, en: 'sad',       es: 'triste',    ru: 'грустный',    translit: 'GRUST-ny',     emoji: '😢' },
  { id: 17, en: 'strong',    es: 'fuerte',    ru: 'сильный',     translit: 'SIL-ny',       emoji: '💪' },
  { id: 18, en: 'weak',      es: 'débil',     ru: 'слабый',      translit: 'SLA-by',       emoji: '🍃' },
  { id: 19, en: 'new',       es: 'nuevo',     ru: 'новый',       translit: 'NO-vy',        emoji: '✨' },
  { id: 20, en: 'long',      es: 'largo',     ru: 'длинный',     translit: 'DLIN-ny',      emoji: '📐' },
  { id: 21, en: 'loud',      es: 'ruidoso',   ru: 'громкий',     translit: 'GROM-kiy',     emoji: '📢' },
  { id: 22, en: 'quiet',     es: 'silencioso',ru: 'тихий',       translit: 'TI-khiy',      emoji: '🤫' },
  { id: 23, en: 'heavy',     es: 'pesado',    ru: 'тяжёлый',     translit: 'tya-ZHYO-ly',  emoji: '🏋️' },
  { id: 24, en: 'light',     es: 'ligero',    ru: 'лёгкий',      translit: 'LYOG-kiy',     emoji: '🪶' },
];
